[[pages]]
path = "pages/home.py"
name = "ContextCare"
icon = "ğŸ "

[[pages]]
path = "pages/add_context.py"
name = "Add Context"
icon = ":books:"

[[pages]]
path = "pages/metrics.py"
name = "Metrics"
icon = "ğŸ“Š"
